<?php

namespace IS\MainBundle\Repository;

/**
 * AchatMarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatMarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReport()
    {
        $rawSql = "SELECT a.fournisseur, u.nom as unite, a.created_at, m.nom, a.prix, a.qte FROM achat_marchandise a
                      JOIN matiere_premiere m
                      ON m.id = a.matiere_id
                      LEFT JOIN unite u ON u.id = a.unite_id
                      ORDER BY DATE(a.created_at) DESC
                    ;";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }

}
