<?php

namespace IS\MainBundle\Repository;

/**
 * DepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($from, $to)
    {
        $rawSql = "SELECT id, created_at, fournisseur, libelle, montant FROM depense

                  WHERE DATE(created_at) BETWEEN '$from 00:00:00' AND '$to 23:59:59'";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }

}
