<?php

namespace IS\MainBundle\Repository;

/**
 * MatierePremiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatierePremiereRepository extends \Doctrine\ORM\EntityRepository
{
}
