<?php

namespace IS\MainBundle\Repository;

/**
 * PortionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortionRepository extends \Doctrine\ORM\EntityRepository
{
}
