<?php

namespace IS\MainBundle\Repository;

/**
 * StockMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockPortionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReportIN()
    {
        $rawSql = "SELECT   m.nom ,
                         SUM(IF (s.taille = 'Large'  AND s.type = 'in', s.qte, 0)) as L,
                         SUM(IF (s.taille = 'Moyen' AND s.type = 'in', s.qte, 0)) as M
                FROM `stock_portion` s
                         JOIN matiere_premiere m
                              ON m.id = s.produit_id
                WHERE m.type = 'Fruit' 
                GROUP BY  s.produit_id
                ;";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }

    public function getReport()
    {
        $rawSql = "SELECT   m.nom ,
                         SUM(IF (  s.type = 'in', s.qte, 0)) as SIN,
                         SUM(IF ( s.type = 'out', s.qte, 0)) as SOUT
                FROM `stock_portion` s
                         JOIN matiere_premiere m
                              ON m.id = s.produit_id
                WHERE m.type = 'Autres' 
                GROUP BY  s.produit_id
                ;";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }
    public function getReportOUT()
    {
        $rawSql = "SELECT   m.nom ,
                         SUM(IF (s.taille = 'Large'  AND s.type = 'out', s.qte, 0)) as L,
                         SUM(IF (s.taille = 'Moyen' AND s.type = 'out', s.qte, 0)) as M
                FROM `stock_portion` s
                         JOIN matiere_premiere m
                              ON m.id = s.produit_id
                WHERE m.type = 'Fruit' 
                GROUP BY  s.produit_id
                ;";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }
    public function getReportReel()
    {
        $rawSql = "SELECT   m.nom ,
  SUM(IF (s.taille = 'Large' AND s.type = 'out', s.qte, 0)) as SL,
  SUM(IF (s.taille = 'Moyen' AND s.type = 'out', s.qte, 0)) as SM,
  SUM(IF (s.taille = 'Large' AND s.type = 'in', s.qte, 0)) as EL,
  SUM(IF (s.taille = 'Moyen' AND s.type = 'in', s.qte, 0)) as EM
FROM `stock_portion` s
  JOIN matiere_premiere m
    ON m.id = s.produit_id
    WHERE m.type = 'Fruit' 
GROUP BY  s.produit_id
;";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }


}
