<?php

namespace IS\MainBundle\Repository;

/**
 * StockMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockMatiereRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReport()
    {
        $rawSql = "SELECT   m.nom , u.nom as unite,
                      SUM(IF (s.type = 'in', s.qte, 0)) as entree,
                      SUM(IF (s.type = 'out', s.qte, 0)) as sortie
                    FROM `stock_matiere` s
                      JOIN matiere_premiere m
                        ON m.id = s.produit_id
                      LEFT JOIN achat_marchandise a on s.achat_id = a.id
                       JOIN unite u 
                      ON u.id = a.unite_id
                    GROUP BY  m.nom";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }

}
