<?php

namespace IS\MainBundle\Repository;

/**
 * VariationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariationRepository extends \Doctrine\ORM\EntityRepository
{
}
