# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  redirect.after.login:
    class: IS\MainBundle\Redirection\AfterLoginRedirection
    arguments: ['@router']