achatmarchandise_index:
    path:     /
    defaults: { _controller: "ISMainBundle:AchatMarchandise:index" }
    methods:  GET

achatmarchandise_show:
    path:     /{id}/show
    defaults: { _controller: "ISMainBundle:AchatMarchandise:show" }
    methods:  GET

achatmarchandise_new:
    path:     /new
    defaults: { _controller: "ISMainBundle:AchatMarchandise:new" }
    methods:  [GET, POST]

achatmarchandise_edit:
    path:     /{id}/edit
    defaults: { _controller: "ISMainBundle:AchatMarchandise:edit" }
    methods:  [GET, POST]

achatmarchandise_delete:
    path:     /{id}/delete
    defaults: { _controller: "ISMainBundle:AchatMarchandise:delete" }
