matiere_index:
    path:     /
    defaults: { _controller: "ISMainBundle:Matiere:index" }
    methods:  GET

matiere_show:
    path:     /{id}/show
    defaults: { _controller: "ISMainBundle:Matiere:show" }
    methods:  GET

matiere_new:
    path:     /new
    defaults: { _controller: "ISMainBundle:Matiere:new" }
    methods:  [GET, POST]

matiere_edit:
    path:     /{id}/edit
    defaults: { _controller: "ISMainBundle:Matiere:edit" }
    methods:  [GET, POST]

matiere_delete:
    path:     /{id}/delete
    defaults: { _controller: "ISMainBundle:Matiere:delete" }

